---
- hosts: local
  connection: local
  become: yes
  gather_facts: yes
  vars:
    app_name: Atom
    app_url: https://github.com/atom/atom/releases/download/v1.35.1/atom-mac.zip
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
