--- # Notification
- hosts: openvpn
  remote_user: openvpnas
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
          - name: install nginx
            apt:
                    name: nginx
                    state: latest
            notify:
            - enable and start nginx service
  handlers:
          - name: enable and start nginx service
            service:
              name: nginx
              enabled: yes
              state: restarted
