---
- hosts: local
  connection: local
  become: yes
  gather_facts: yes
  vars:
    app_name: Spectacle
    app_url: https://s3.amazonaws.com/spectacle/downloads/Spectacle+1.2.zip
    installer_type: app
    install_method: dmg
    download_file_type: dmg
  roles:
    - setup
    - installer
    - cleanup
